apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rnhy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rnhy
    app.kubernetes.io/part-of: tkrw-pr712-0075-0044-app
  name: devfile-sample-rnhy
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rnhy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rnhy
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0044-tenant/tkrw-pr712-0075-0044-app/devfile-sample-rnhy@sha256:6c16f3ecec7be8abc0cb5d29ffcdac7aff9b6ffc8fa08d96c3564f4fa28bb91a
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
